const linhas_amigurumi = [
    {
        id: 1,
        nome: "Natural",
        cod: "20",
        imagem: "assets/cores/20-natural.png",
    },
    {
        id: 2,
        nome: "Creme",
        cod: "1112",
        imagem: "assets/cores/1112-creme.png",
    },

    {
        id: 100,
        nome: "Magnolia",
        cod: "1205",
        imagem: "assets/cores/1205-magnolia.png",
    },

    {
        id: 3,
        nome: "Canário",
        cod: "1289",
        imagem: "assets/cores/1289-canario.png",
    },
    {
        id: 4,
        nome: "Solar",
        cod: "1317",
        imagem: "assets/cores/1317-solar.png",
    },
    {
        id: 5,
        nome: "Amarelo Candy",
        cod: "1730",
        imagem: "assets/cores/1730-amarelocandy.png",
    },
    {
        id: 6,
        nome: "Azul Candy",
        cod: "2012",
        imagem: "assets/cores/2012-azulcandy.png",
    },
    {
        id: 7,
        nome: "Hortênsia",
        cod: "2137",
        imagem: "assets/cores/2137-hortensia.png",
    },
    {
        id: 8,
        nome: "Turquesa",
        cod: "2194",
        imagem: "assets/cores/2194-turquesa.png",
    },
    {
        id: 9,
        nome: "Verde Candy",
        cod: "2204",
        imagem: "assets/cores/2204-verdecandy.png",
    },
    {
        id: 10,
        nome: "Acqua",
        cod: "2500",
        imagem: "assets/cores/2500-acqua.png",
    },
    {
        id: 11,
        nome: "Planeta",
        cod: "2618",
        imagem: "assets/cores/2618-planeta.png",
    },
    {
        id: 12,
        nome: "Marinheiro",
        cod: "2745",
        imagem: "assets/cores/2745-marinheiro.png",
    },
    {
        id: 13,
        nome: "Azul Bic",
        cod: "2829",
        imagem: "assets/cores/2829-azulbic.png",
    },
    {
        id: 14,
        nome: "Anil Profundo",
        cod: "2856",
        imagem: "assets/cores/2856-anilprofundo.png",
    },
    {
        id: 15,
        nome: "Aquário",
        cod: "2927",
        imagem: "assets/cores/2927-aquario.png",
    },
    {
        id: 16,
        nome: "Netuno",
        cod: "2930",
        imagem: "assets/cores/2930-netuno.png",
    },
    {
        id: 17,
        nome: "Náutico",
        cod: "2931",
        imagem: "assets/cores/2931-nautico.png",
    },
    {
        id: 18,
        nome: "Doçura",
        cod: "3046",
        imagem: "assets/cores/3046-docura.png",
    },
    {
        id: 19,
        nome: "Sopro",
        cod: "3047",
        imagem: "assets/cores/3047-sopro.png",
    },
    {
        id: 20,
        nome: "Flamingo",
        cod: "3048",
        imagem: "assets/cores/3048-flamingo.png",
    },
    {
        id: 21,
        nome: "Gardenia",
        cod: "3061",
        imagem: "assets/cores/3061-gardenia.png",
    },
    {
        id: 22,
        nome: "Quartzo",
        cod: "3077",
        imagem: "assets/cores/3077-quartzo.png",
    },
    {
        id: 23,
        nome: "Chiclete",
        cod: "3131",
        imagem: "assets/cores/3131-chiclete.png",
    },
    {
        id: 24,
        nome: "Macadâmia",
        cod: "3148",
        imagem: "assets/cores/3148-macadamia.png",
    },
    {
        id: 25,
        nome: "Vinho",
        cod: "3154",
        imagem: "assets/cores/3154-vinho.png",
    },
    {
        id: 26,
        nome: "Roseira",
        cod: "3157",
        imagem: "assets/cores/3157-roseira.png",
    },

    {
        id: 27,
        nome: "Pitaya",
        cod: "3182",
        imagem: "assets/cores/3182-pitaya.png",
    },
    {
        id: 28,
        nome: "Camafeu",
        cod: "3201",
        imagem: "assets/cores/3201-camafeu.png",
    },
    {
        id: 29,
        nome: "Tulipa",
        cod: "3334",
        imagem: "assets/cores/3334-tulipa.png",
    },
    {
        id: 30,
        nome: "Vermelho Círculo",
        cod: "3402",
        imagem: "assets/cores/3402-vermelhocirculo.png",
    },
    {
        id: 31,
        nome: "Carmim",
        cod: "3528",
        imagem: "assets/cores/3528-carmim.png",
    },
    {
        id: 32,
        nome: "Cereja",
        cod: "3583",
        imagem: "assets/cores/3583-cereja.png",
    },
    {
        id: 33,
        nome: "Rubi",
        cod: "3611",
        imagem: "assets/cores/3611-rubi.png",
    },
    {
        id: 34,
        nome: "Rosa Pink",
        cod: "3754",
        imagem: "assets/cores/3754-rosapink.png",
    },
    {
        id: 35,
        nome: "Viva Magenta",
        cod: "3951",
        imagem: "assets/cores/3951-vivamagenta.png",
    },
    {
        id: 36,
        nome: "Organza",
        cod: "4092",
        imagem: "assets/cores/4092-organza.png",
    },
    {
        id: 37,
        nome: "Tafetá",
        cod: "4093",
        imagem: "assets/cores/4093-tafeta.png",
    },
    {
        id: 38,
        nome: "Cetim",
        cod: "4094",
        imagem: "assets/cores/4094-cetim.png",
    },
    {
        id: 39,
        nome: "Rum",
        cod: "4095",
        imagem: "assets/cores/4095-rum.png",
    },
    {
        id: 40,
        nome: "Dark Cheddar",
        cod: "4131",
        imagem: "assets/cores/4131-darkcheddar.png",
    },
    {
        id: 41,
        nome: "Gema",
        cod: "4146",
        imagem: "assets/cores/4146-gema.png",
    },
    {
        id: 42,
        nome: "Dália",
        cod: "4168",
        imagem: "assets/cores/4168-dalia.png",
    },
    {
        id: 43,
        nome: "Tropicália",
        cod: "4171",
        imagem: "assets/cores/4171-tropicalia.png",
    },
    {
        id: 44,
        nome: "Peach Fuzz",
        cod: "4224",
        imagem: "assets/cores/4224-peachfuzz.png",
    },
    {
        id: 45,
        nome: "Tangerina",
        cod: "4445",
        imagem: "assets/cores/4445-tangerina.png",
    },
    {
        id: 46,
        nome: "Tijolo",
        cod: "4448",
        imagem: "assets/cores/4448-tijolo.png",
    },
    {
        id: 47,
        nome: "Laranja",
        cod: "4456",
        imagem: "assets/cores/4456-laranja.png",
    },
    {
        id: 48,
        nome: "Petróleo",
        cod: "5073",
        imagem: "assets/cores/5073-petroleo.png",
    },
    {
        id: 49,
        nome: "Hera",
        cod: "5076",
        imagem: "assets/cores/5076-hera.png",
    },
    {
        id: 50,
        nome: "Eco",
        cod: "5083",
        imagem: "assets/cores/5083-eco.png",
    },
    {
        id: 51,
        nome: "Selva",
        cod: "5089",
        imagem: "assets/cores/5089-selva.png",
    },
    {
        id: 52,
        nome: "Celeste",
        cod: "5091",
        imagem: "assets/cores/5091-celeste.png",
    },
    {
        id: 53,
        nome: "Greenery",
        cod: "5203",
        imagem: "assets/cores/5203-greenery.png",
    },

    {
        id: 54,
        nome: "Militar",
        cod: "5368",
        imagem: "assets/cores/5368-militar.png",
    },
    {
        id: 55,
        nome: "Musgo",
        cod: "5398",
        imagem: "assets/cores/5398-musgo.png",
    },
    {
        id: 56,
        nome: "Verde Limão",
        cod: "5583",
        imagem: "assets/cores/5583-verdelimao.png",
    },
    {
        id: 57,
        nome: "Tiffany",
        cod: "5669",
        imagem: "assets/cores/5669-tiffany.png",
    },
    {
        id: 58,
        nome: "Periquito",
        cod: "5741",
        imagem: "assets/cores/5741-periquito.png",
    },
    {
        id: 59,
        nome: "Neo Mint",
        cod: "5743",
        imagem: "assets/cores/5743-neomint.png",
    },
    {
        id: 60,
        nome: "Eucalipto",
        cod: "5745",
        imagem: "assets/cores/5745-eucalipto.png",
    },
    {
        id: 61,
        nome: "Bandeira",
        cod: "5767",
        imagem: "assets/cores/5767-bandeira.png",
    },
    {
        id: 62,
        nome: "Pistache",
        cod: "5800",
        imagem: "assets/cores/5800-pistache.png",
    },
    {
        id: 63,
        nome: "Limonada",
        cod: "5806",
        imagem: "assets/cores/5806-limonada.png",
    },
    {
        id: 64,
        nome: "Lilás Candy",
        cod: "6006",
        imagem: "assets/cores/6006-lilascandy.png",
    },
    {
        id: 65,
        nome: "Místico",
        cod: "6030",
        imagem: "assets/cores/6030-mistico.png",
    },
    {
        id: 66,
        nome: "Realeza",
        cod: "6034",
        imagem: "assets/cores/6034-realeza.png",
    },
    {
        id: 67,
        nome: "Violeta",
        cod: "6161",
        imagem: "assets/cores/6161-violeta.png",
    },
    {
        id: 68,
        nome: "Tecno",
        cod: "6201",
        imagem: "assets/cores/6201-tecno.png",
    },
    {
        id: 69,
        nome: "Azaleia",
        cod: "6399",
        imagem: "assets/cores/6399-azaleia.png",
    },
    {
        id: 70,
        nome: "Alfazema",
        cod: "6614",
        imagem: "assets/cores/6614-alfazema.png",
    },
    {
        id: 71,
        nome: "Malva",
        cod: "6802",
        imagem: "assets/cores/6802-malva.png",
    },
    {
        id: 72,
        nome: "Mostarda",
        cod: "7030",
        imagem: "assets/cores/7030-mostarda.png",
    },
    {
        id: 73,
        nome: "Pedra Quente",
        cod: "7066",
        imagem: "assets/cores/7066-pedraquente.png",
    },
    {
        id: 74,
        nome: "Centeio",
        cod: "7072",
        imagem: "assets/cores/7072-centeio.png",
    },
    {
        id: 75,
        nome: "Caramelito",
        cod: "7076",
        imagem: "assets/cores/7076-caramelito.png",
    },
    {
        id: 76,
        nome: "Doce de Leite",
        cod: "7077",
        imagem: "assets/cores/7077-docedeleite.png",
    },
    {
        id: 77,
        nome: "Pimenta Rosa",
        cod: "7078",
        imagem: "assets/cores/7078-pimentarosa.png",
    },
    {
        id: 78,
        nome: "Marsala",
        cod: "7136",
        imagem: "assets/cores/7136-marsala.png",
    },
    {
        id: 79,
        nome: "Craft",
        cod: "7148",
        imagem: "assets/cores/7148-craft.png",
    },
    {
        id: 80,
        nome: "Tâmara",
        cod: "7220",
        imagem: "assets/cores/7220-tamara.png",
    },
    {
        id: 81,
        nome: "Brownie",
        cod: "7400",
        imagem: "assets/cores/7400-brownie.png",
    },
    {
        id: 82,
        nome: "Chantilly",
        cod: "7563",
        imagem: "assets/cores/7563-chantilly.png",
    },
    {
        id: 83,
        nome: "Porcelana",
        cod: "7564",
        imagem: "assets/cores/7564-porcelana.png",
    },
    {
        id: 84,
        nome: "Cacau",
        cod: "7567",
        imagem: "assets/cores/7567-cacau.png",
    },
    {
        id: 85,
        nome: "Brigadeiro",
        cod: "7569",
        imagem: "assets/cores/7569-brigadeiro.png",
    },
    {
        id: 86,
        nome: "Castor",
        cod: "7603",
        imagem: "assets/cores/7603-castor.png",
    },
    {
        id: 87,
        nome: "Castanha",
        cod: "7625",
        imagem: "assets/cores/7625-castanha.png",
    },
    {
        id: 88,
        nome: "Amêndoa",
        cod: "7650",
        imagem: "assets/cores/7650-amendoa.png",
    },
    {
        id: 89,
        nome: "Lenha",
        cod: "7713",
        imagem: "assets/cores/7713-lenha.png",
    },
    {
        id: 90,
        nome: "Branco",
        cod: "8001",
        imagem: "assets/cores/8001-branco.png",
    },
    {
        id: 91,
        nome: "Pedreira",
        cod: "8008",
        imagem: "assets/cores/8008-pedreira.png",
    },
    {
        id: 92,
        nome: "Glacial",
        cod: "8013",
        imagem: "assets/cores/8013-glacial.png",
    },
    {
        id: 93,
        nome: "Matrix",
        cod: "8069",
        imagem: "assets/cores/8069-matrix.png",
    },
    {
        id: 94,
        nome: "Off-White",
        cod: "8176",
        imagem: "assets/cores/8176-offwhite.png",
    },
    {
        id: 95,
        nome: "Índigo",
        cod: "8736",
        imagem: "assets/cores/8736-indigo.png",
    },
    {
        id: 96,
        nome: "Aço",
        cod: "8797",
        imagem: "assets/cores/8797-aco.png",
    },
    {
        id: 97,
        nome: "Preto",
        cod: "8990",
        imagem: "assets/cores/8990-preto.png",
    },
    {
        id: 98,
        nome: "Lhama",
        cod: "9278",
        imagem: "assets/cores/9278-lhama.png",
    },

    {
        id: 99,
        nome: "Unicórnio",
        cod: "9534",
        imagem: "assets/cores/9534-unicornio.png",
    }

];